Got dims calls working in add and multiply
some error handling is done too

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -90,10 +90,6 @@ rm -f temp
 
 transpose () {
 
-#    for (( i=1; i <= $col_count; i++))
-# 		do cut -f $i $arg2 | tr $'\n' $'\t' | sed -e "s/\t$/\n/g" >> transposed
-# 	done
-
 while read line
 do
   for i in $line
@@ -103,8 +99,6 @@ do
   echo -e >> temp
 done < "${1:-/dev/stdin}"
 
-echo "This is from transpose"
-cat temp
 counter=0
 
 #loop through the temp file to count all elements 
@@ -191,9 +185,18 @@ add (){
 	done < "${2:-/dev/stdin}"
 	
 	mat1dims=$(dims mat1)
-	echo $mat1dims
+	mat2dims=$(dims mat2)
 
-	col_count=5
+	if [ "$mat1dims" != "$mat2dims" ]; then
+		echo "Error. Dimensional mismatch."
+		rm -f mat1 mat2
+		exit 21
+	fi
+
+	set -- $mat1dims
+	col_count=$2
+	((col_count++))
+
 	while read <&3 file1 && read <&4 file2
 	do
 		i=1
@@ -231,7 +234,19 @@ multiply() {
 	  echo -e >> mat2
 	done < "${2:-/dev/stdin}"
 
-	col_count=5
+	mat1dims=$(dims mat1)
+	mat2dims=$(dims mat2)
+
+	if [ "$mat1dims" != "$mat2dims" ]; then
+		echo "Error. Dimensional mismatch."
+		rm -f mat1 mat2
+		exit 21
+	fi
+
+	set -- $mat1dims
+	col_count=$2
+	((col_count++))
+
 	while read <&3 file1 && read <&4 file2
 	do
 		i=1
