mean mostly working now, need to fix trailing tabs

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -19,6 +19,7 @@ mismatchError=$(echo "Error. Dimensional mismatch.")
 
 temp=temporary$$
 temp2=temporary2$$
+temp3=temporary3$$
 mat1=matrix1$$
 mat2=matrix2$$
 transposed=trans$$
@@ -26,37 +27,43 @@ transposed2=transposed2$$
 average=avg$$
 matrix_sum=mat_sum$$
 results=result$$
+final=finalresults$$
 
 trap 'rm -f $temp $temp2 $results $transposed $transposed2 $average $results; exit 1' INT HUP TERM
 
-# check to see if there is an operation selected to perform, if not throw an error
-if [[ "$1" != "" ]]; then
-    arg1="$1"
-else
-    echo "$unavailableError"
-fi
-
-#check to see if there is a second argument and assign it if it exists
-#TODO: figure out if this file is readable or not
-if [[ "$2" != "" ]]; then
-    arg2="$2"
-fi
-
-#check to see if there is a third argument and assign it if it exists
-#TODO: figure out if this file is readable or not
-if [[ "$3" != "" ]]; then
-    arg3="$3"
-fi
-
-#echo "$arg1"
-
-# if [[ $arg1 == "" ]];
-# 	then
-# 		echo "$errorMessage"
+# # check to see if there is an operation selected to perform, if not throw an error
+# if [[ "$1" != "" ]]; then
+#     arg1="$1"
+# else
+#     echo "$unavailableError"
+#     exit 21
 # fi
+
+# #check to see if there is a second argument and assign it if it exists
+# #TODO: figure out if this file is readable or not
+# if [[ "$2" != "" ]]; then
+#     arg2="$2"
+# fi
+
+# #check to see if there is a third argument and assign it if it exists
+# #TODO: figure out if this file is readable or not
+# if [[ "$3" != "" ]]; then
+#     arg3="$3"
+# fi
+
+# #echo "$arg1"
+
+# # if [[ $arg1 == "" ]];
+# # 	then
+# # 		echo "$errorMessage"
+# # fi
 
 function dims () {
 
+if [[ "$2" != "" ]]; then
+    echo "Error. Too many arguments."
+    exit 21
+fi
 #if a file exists, read from it and make a copy to use in temp file
 #if not, get input from stdin and copy that over to a temp file
 while read line
@@ -90,41 +97,36 @@ rm -f temp
 
 transpose () {
 
+if [[ "$2" != "" ]]; then
+    echo "Error. Too many arguments."
+    exit 21
+fi
+
 while read line
 do
   for i in $line
   do
-  	echo -e -n "$i \t" >> temp
+  	echo -e -n "$i \t" >> temp2
   done
-  echo -e >> temp
+  echo -e >> temp2
 done < "${1:-/dev/stdin}"
 
-counter=0
+matdims=$(dims temp2)
+set -- $matdims
+col_count=$2
 
-#loop through the temp file to count all elements 
-while read row
-do
-	for i in $row
-	do
-		((counter++))
-	done
-done < temp
-
-row_count=$(wc -l < temp)
-col_count=$(($counter/$row_count))
-
-   for (( i=1; i <= $col_count; i++)) # previously <=
-		do cut -f $i temp | tr "\n" "\t" >> transposed
+   for (( i=1; i <= $col_count; i++))
+		do cut -f $i temp2 | tr "\n" "\t" >> transposed
 		echo -e >> transposed
 	done
 
 cat transposed
-rm -f temp transposed
+rm -f temp2 transposed
 
 }
 
 
-#TODO: format the mean to appear as a row matrix
+# #TODO: format the mean to appear as a row matrix
 mean() {
    
 	# define some variables to hold temporary files
@@ -134,16 +136,18 @@ mean() {
 	do
 	  for i in $line
 	  do
-	  	echo -e -n "$i \t" >> temp2
+	  	echo -e -n "$i \t" >> temp3
 	  done
-	  echo -e >> temp2
+	  echo -e >> temp3
 	done < "${1:-/dev/stdin}"
 
    # transpose the matrix so we can perform the summation on each row
-   transpose temp2 >> transposed2
-
+   transpose temp3 >> transposed2
    #loop through the transposed matrix and sum all values in the row
 
+   	matdims=$(dims temp3)
+	set -- $matdims
+	row_count=$1
    sums=0
    val=0
    while read row
@@ -158,13 +162,22 @@ mean() {
    	val=0
    done < transposed2
 
-   cat average | tr '\n' '\t' > results
-   cat results
-   rm -f average transposed2 temp2 results
+   paste -s average 
+   #cat average
+   # cat average | tr '\n' '\t' >> results
+   # echo -e >> results
+   # cat results
+   rm -f average transposed2 temp3 #results
 }
 
 add (){
    #read file in $1
+
+   if [[ "$2" == "" ]]; then
+    echo "Error. No argument present."
+    exit 21
+	fi
+
    while read line
 	do
 	  for i in $line
@@ -173,6 +186,7 @@ add (){
 	  done
 	  echo -e >> mat1
 	done < "${1:-/dev/stdin}"
+	
 	
 	#read file in $2
 	while read line
@@ -205,14 +219,16 @@ add (){
 			left=$(echo "$file1" | cut -f"$i")
 			right=$(echo "$file2" | cut -f"$i")
 			sums=$((($left+$right)))
-			echo -ne "$sums \t"
+			echo -ne "$sums\t" >> results #try using paste to a file here, trailing tabs is probably the issue
 			i=$[$i+1]
 		done
-		echo -e 
+		echo -e >> results
 	done 3<mat1 4<mat2
 
-	rm -f mat1 mat2
+	paste -s results
+	rm -f mat1 mat2 
 }
+
 multiply() {
    #read file in $1
    while read line
